allow reading the stored/raw timestamp value of a Block
Matroska-Org/libmatroska pull request #52
Opened 2020-11-11 14:21 UTC by robUx4

Given the API to get the GlobalTimecode of a Block doesn't handle the floating
point value of the TrackTimestampScale (attaching a parent track is not common
and even though the value is not directly available unlike a fractional
timestampscale), it allows external code to compute the proper timestamp
when TrackTimestampScale is not 1.0.

Ultimately the whole way of computing the GlobalTimecode of a block should change but that's probably for a v2.0

2020-11-11 14:27 UTC, robUx4 commented
The branch using this code in VLC to use the `TrackTimestampScale` https://code.videolan.org/robUx4/vlc/-/commits/mkv-track-scale

2021-02-18 09:37 UTC, mbunkus requested changes

2021-02-18 09:37 UTC, mbunkus commented on matroska/KaxBlock.h
> +#define KAX_BLOCK_STORE_TIMESTAMP
Huh? That `#define` isn't used in your PR, and it doesn't exist in the repository at the moment. Probably left in accidentally?

2021-02-18 09:37 UTC, mbunkus commented on matroska/KaxBlock.h
> +    int16 GetStoredTimestamp() const { return LocalTimecode; }
I'd prefer a slightly different name. Maybe `GetRelativeTimestamp`? "relative" is the term we use in the Matroska spec, too.

2021-02-19 07:00 UTC, robUx4 commented on matroska/KaxBlock.h
> +#define KAX_BLOCK_STORE_TIMESTAMP
It's a way for the host app to tell whether it can use the extra method or not (ie ifdef the code depending on the libmatroska version).

2021-02-19 07:00 UTC, robUx4 commented on matroska/KaxBlock.h
> +    int16 GetStoredTimestamp() const { return LocalTimecode; }
OK

2021-02-19 10:40 UTC, mbunkus commented on matroska/KaxBlock.h
> +#define KAX_BLOCK_STORE_TIMESTAMP
Well, we don't do that for anything else (e.g. availability of certain new classes such as `KaxFlagVisualImpaired`). The usual way to check for availability of certain features is either a check at configuration time (that's how it's done with the traditional `autoconf` approach; compile a short test program that uses the function & `#define` a value in `config.h` if it succeeds) or a compile-time check for the version number (`#if LIBMATROSKA_VERSION >= 0x010603`).

2021-02-21 09:23 UTC, robUx4 commented on matroska/KaxBlock.h
> +#define KAX_BLOCK_STORE_TIMESTAMP
Ah yes, there is LIBMATROSKA_VERSION. I'll use that.

2021-02-21 10:06 UTC, mbunkus approved these changes
After reading up once more on [what you can do with C++ libs without breaking the ABI](https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C++) it seems that this change doesn't actually break the ABI; it's the first point of the "you can" list:

> add new non-virtual functions, including signals and slots and constructors, that do not overload non-overloaded functions.

So yeah, this is fine. Thanks.

2021-02-21 14:50 UTC, merged