clang-tidy fixes
Matroska-Org/libmatroska pull request #57
Opened 2021-03-04 00:15 UTC by neheb

2021-03-04 12:30 UTC, mbunkus requested changes
Thanks. All tests in the MKVToolNix test suite fail. A simple `mkvmerge -o out.mka in.mp3` segfaults.

Please investigate why this happens. Thanks.

2021-05-19 01:05 UTC, neheb commented
Most likely clang-tidy: make member functions const

2022-09-24 21:38 UTC, neheb commented
@mbunkus removed offending commit. I expect tests to pass now.

2022-09-24 21:48 UTC, mbunkus commented
Thanks. From a cursory look the changes seem OK to me, but I still need to test them.

One thing I'm curious about: some variable declarations are converted to `auto` (which I like), while a lot of others that have been touched haven't been — even though it would make so much sense for them, too! For example:

```c++
    const KaxInternalBlock& MyBlock = *static_cast<KaxBlock *>(this->FindElt(EBML_INFO(KaxBlock)));
```

Why not for all of those, too?

2022-09-24 22:14 UTC, neheb commented
@mbunkus So that clang-tidy check's fix routing adds const to the east. I had to manually fix it up. The autos were manually added as I thought they looked cleaner. I'll look into the others.

2022-09-24 22:29 UTC, neheb commented
@mbunkus fixed.

2022-09-24 22:38 UTC, mbunkus commented
Thanks. I'll look some more at it tomorrow.

One thing I'd like you to change already: all those changes to the `enums` in `KaxSemantic.h`. That file is auto-generated from the Matroska specs XML file with tools outside this repo. I'll adjust those to make those changes instead. Thanks.

2022-09-24 22:39 UTC, neheb commented
Added an extra const commit.

2022-09-24 22:39 UTC, neheb commented
Removed typedef commit.

2022-09-25 01:51 UTC, neheb commented
out of curiosity, why does the code use *static_cast<X*>(y) instead of X(y) ?

2022-09-25 02:12 UTC, neheb commented
@robUx4 know something about the last commit?

2022-09-25 05:16 UTC, robUx4 commented
> out of curiosity, why does the code use
> 
> ```
>  *static_cast<X*>(&y)
> ```
> 
> instead of X(y) ? That smells like an old MSVC compiler bug.

That would be to avoid using pointers further down. I'm not against this change but doesn't improve the code much, nor is related to clang-tidy fixes (or it's not mentioned in the commit).

2022-09-25 05:23 UTC, neheb commented
it's not prefixed with clang-tidy, no. It was something I noticed after handling @mbunkus 's comments.

My thinking was it was some bugfix similar to https://github.com/Exiv2/exiv2/commit/3662c29f16

IIRC, you use old compilers.

2022-09-25 09:49 UTC, mbunkus commented
Just tested the current commits: they fail miserably with memory errors all over (access out of bounds etc.). Will investigate, though probably not before the next release of libMatroska. Please don't merge for the time being.

2022-09-26 20:41 UTC, mbunkus requested changes
With the fixes to all four places the MKVToolNix test suit finally runs without issues.

2022-09-26 20:41 UTC, mbunkus commented on src/KaxBlock.cpp
> +  for (size_t i=myBuffers.size()-1; i>=0; i--) {
This commit, or rather this change, is responsible for some of the crashes. And it's rather easy to see why: `myBuffers` can be empty, meaning that `myBuffers.size()-1` will lead to an integer underflow with an unsigned `i`, leading to invalid memory accesses.

Additionally, you really cannot use `i>=0` as the check with unsigned variables. It'll always leads to an integer underflow, 'cause when `i==0` the loop will be run as `i==0` obviously satisfies `i>=0`, and afterwards `i--` will underflow, wrapping back around to `std::numeric_limits<size_t>::max()`, meaning it'll run as an endless loop, accessing out-of-bounds memory.

This whole chunk is just wrong. Either do an explicit cast to `int`, which would be fine, or use this:

```c++
  for (size_t i = myBuffers.size(); i > 0; i--) {
    // now always access as [i-1]
  }
```

I hate both variants, but it's what we got in C & C++, and as it's less code to fix & reason about, I prefer:

```c++
  for (int i=static_cast<int>(myBuffers.size())-1; i>=0; i--) {
```

with the rest unchanged. You don't even have to check for `.isEmpty()`.

2022-09-26 20:41 UTC, mbunkus commented on src/KaxCues.cpp
> +  auto pr = myTempReferences;
This creates a _copy_ of `myTempReferences`. In this place this isn't harmful, but it does cost some performance unnecessarily. Please use a reference instead.

2022-09-26 20:41 UTC, mbunkus commented on src/KaxCues.cpp
> +  auto pr = myTempReferences;
This creates a _copy_ of `myTempReferences`. In this place this _is_ actually harmful, as the iterator is later used in `myTempReference.erase(it)` — but after your change the `it` iterator belongs to a different object. Again, just use a reference instead.

2022-09-26 20:41 UTC, mbunkus commented on src/KaxBlock.cpp
> +  auto myDuration = *static_cast<KaxBlockDuration *>(FindFirstElt(EBML_INFO(KaxBlockDuration), true));
This creates a _copy_ of the element, leading to invalid code execution. Please re-add the reference.

This bad change is modified further in the next commit, "remove unnecessary references". That chunk must be adjusted accordingly.

2022-09-26 20:49 UTC, neheb commented on src/KaxBlock.cpp
> +  auto myDuration = *static_cast<KaxBlockDuration *>(FindFirstElt(EBML_INFO(KaxBlockDuration), true));
Fixed.

2022-09-26 20:49 UTC, neheb commented on src/KaxCues.cpp
> +  auto pr = myTempReferences;
Fixed.

2022-09-26 20:49 UTC, neheb commented on src/KaxCues.cpp
> +  auto pr = myTempReferences;
Fixed.

2022-09-26 20:50 UTC, neheb commented on src/KaxBlock.cpp
> +  for (size_t i=myBuffers.size()-1; i>=0; i--) {
Got rid of the commit.

2022-09-26 20:54 UTC, mbunkus commented on src/KaxBlock.cpp
> +  for (size_t i=myBuffers.size()-1; i>=0; i--) {
The other hunks of that commit were fine; only this one hunk was problematic.

Even though the other hunks also used a `size_t` with `myBuffers.size() - 1`, it couldn't actually underflow as there's a check for `myBuffers.size() <= 1` with a subsequent `return` before those `- 1` calculations.

2022-09-26 20:57 UTC, merged

2022-09-26 20:58 UTC, mbunkus commented
Thanks, this is fine now. Merged.

2022-09-27 15:12 UTC, mbunkus commented
True. It did initially, though not anymore.