avoid some implicit conversions
Matroska-Org/libmatroska pull request #76
Opened 2022-09-26 22:07 UTC by neheb

2022-09-27 15:51 UTC, robUx4 commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
I don't understand the need for a `static_cast<>` here. KaxBlockBlob has a `operator const KaxInternalBlock &() const`.

2022-09-27 22:00 UTC, neheb commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
As is, it makes no difference because of auto. It's a compiler error fix when running google-explicit-constructor with clang-tidy

2022-10-02 07:29 UTC, robUx4 commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
So just use `auto` ?

2022-10-02 08:33 UTC, neheb commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
But that's a copy, not a reference

2022-10-02 09:47 UTC, mbunkus commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
`RefdBlock` is of type `KaxBlockBlob`. `KaxBlockBlob` itself doesn't have a function called `GlobalTimecode()`. However, it does have an `operator KaxInternalBlock` to retrieve that type of block, which does have the desired `GlobalTimecode()` function.

Therefore we do need a cast. The only reason to use a `static_cast` here instead of that C-style cast is that it's clearer in expressing its intent: the author didn't just get the data type wrong. Also it's easier to search for such types of casts, e.g. with `grep`.

I'm fine with such changes.

Preferably I'd also use `SetValue(…)` in the next line instead of `*static_cast<EbmlSInteger *>(this) = `, as again, this is much clearer in what it actually does. The `SetValue()` functions were introduced much later than the original, `operator`-based setting, though, and this code predates the introduction of `SetValue(…)`.

Example:

```c++
    const auto &block = static_cast<const KaxInternalBlock &>(*RefdBlock);
    SetValue(static_cast<int64>(block.GlobalTimecode()) - static_cast<int64>(ParentBlock->GlobalTimecode()) / static_cast<int64>(ParentBlock->GlobalTimecodeScale()));
```

(Yes, I've tested my example with the MKVToolNix test suite)

2022-10-02 17:38 UTC, neheb commented
CI failure is due to missing libebml 1.4.3

2022-10-02 18:06 UTC, mbunkus requested changes

2022-10-02 18:06 UTC, mbunkus commented on src/KaxSeekHead.cpp
> +  if (it != this->end()) {
This change is nice, sure, but as you're already doing the "early return" pattern in commits such as "no return after else", it would fit nicely here, too:

```c++
  if (it == this->end())
    return nullptr;

  auto it2 = …
```

2022-10-02 18:06 UTC, mbunkus commented on src/KaxBlockData.cpp
> +    auto block = reinterpret_cast<const KaxInternalBlock*>(RefdBlock);
This is wrong.

What the original `static_cast<const KaxInternalBlock &>(*RefdBlock)` does is calling `KaxBlockBlob::operator KaxInternalBlock const()`. This function does NOT just converts the address of the object to a different pointer type. Instead it uses `GetChild<>()` to create a new object & return its address (highly simplified). See [the source](https://github.com/Matroska-Org/libmatroska/blob/master/src/KaxBlock.cpp#L887).

The `reinterpret_cast<>` on the other hand simply starts treating the object at that address as something else. And that's plain wrong. It'll surely segfault.

Same for the other change in this commit.

This whole commit is plain wrong. Please drop it.

2022-10-02 18:14 UTC, neheb commented on src/KaxBlockData.cpp
> +    auto block = reinterpret_cast<const KaxInternalBlock*>(RefdBlock);
Dropped.

2022-10-02 18:14 UTC, neheb commented on src/KaxSeekHead.cpp
> +  if (it != this->end()) {
Done.

2022-10-02 18:14 UTC, neheb commented on matroska/KaxVersion.h
> +const std::string KaxCodeDate = "Unknown";
Dropped.

2022-10-02 18:15 UTC, neheb commented on src/KaxBlockData.cpp
> +    const auto &block = static_cast<const KaxInternalBlock&>(*RefdBlock);
Made this change.

2022-10-02 19:38 UTC, mbunkus approved these changes
Compiles & passes the MKVToolNix test suite. This LGTM now.

2022-10-03 09:53 UTC, merged