clang-tidy: remove non const operator
Matroska-Org/libmatroska pull request #92
Opened 2022-10-15 16:04 UTC by neheb

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2022-10-15 16:18 UTC, mbunkus requested changes

2022-10-15 16:18 UTC, mbunkus commented on src/KaxCluster.cpp
> +        PushElement(simple);
This is wrong. The original code simply passes a memory address along (in form of a reference), while your change will make copies of objects.

2022-10-15 16:18 UTC, mbunkus commented on src/KaxCluster.cpp
> +          if (static_cast<std::size_t>(std::distance(Blobs.begin(), it)) == ListSize()) {
The more idiomatic and easier to understand way to write this is `if (it == Blobs.end()) {`.

2022-10-15 16:18 UTC, mbunkus commented on src/KaxCluster.cpp
> +          auto it = std::find_if(Blobs.begin(), Blobs.end(), [=](auto b){ return static_cast<const KaxInternalBlock&>(*b).TrackNum() == tracknum; });
Please name the values to copy into the lamba explicitly, e.g. `…, [=tracknum](auto b){ …` That's much more explicit, and it'll never lead to accidentally making copies of objects one might not have wanted to copy if there are ever changes to the lambda's code.

2022-10-15 16:20 UTC, neheb commented on src/KaxCluster.cpp
> +          if (static_cast<std::size_t>(std::distance(Blobs.begin(), it)) == ListSize()) {
I wasn't sure if ListSize() is equivalent.

2022-10-15 16:24 UTC, neheb commented
Removed first commit.

2022-10-15 16:28 UTC, mbunkus commented on src/KaxCluster.cpp
> +          if (static_cast<std::size_t>(std::distance(Blobs.begin(), it)) == ListSize()) {
The longer I look at this code the more I'm convinced the original code was actually buggy. The function `ListSize()` is only defined in the `EbmlMaster` class and never overridden. It simply returns `ElementList.size()`.

However, this piece of code looks through a different vector, `Blobs`, a member of the `KaxCluster` class.

The code should probably have read `if (Index == Blobs.ListSize()) {` before, making `if (it == Blobs.end()) {` even more correct than I initially thought.

2022-10-15 16:30 UTC, mbunkus commented on src/KaxCluster.cpp
> +          if (static_cast<std::size_t>(std::distance(Blobs.begin(), it)) == ListSize()) {
The reason why no one ever noticed is that the code is only run if `bSilentTracksUsed` is `true`, and I don't think there's any program that actually uses this "silent tracks" feature…

2022-10-15 16:34 UTC, neheb commented on src/KaxCluster.cpp
> +          if (static_cast<std::size_t>(std::distance(Blobs.begin(), it)) == ListSize()) {
I noticed there are a bunch of files in test/ that don't work. They need updating it seems.

There are even unicode issues in some of them that prevents GCC from compiling.

2022-10-16 10:42 UTC, merged

2022-10-16 10:42 UTC, mbunkus commented
Thanks.